
# see: https://spring.io/guides/topicals/spring-boot-docker/
# see: https://hub.docker.com/_/eclipse-temurin
FROM eclipse-temurin:8-jdk-alpine

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

ARG JAR_FILE=target/qon-demo-springboot.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
