
# Define the primary Logging Implementation Class
#org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog

# By default, log at INFO level all Jetty classes.
org.eclipse.jetty.LEVEL=INFO
#org.eclipse.jetty.LEVEL=DEBUG
#org.eclipse.jetty.LEVEL=WARN

# Classes with distinct logging level
org.apache.commons.beanutils.converters=INFO

# Skip Warnings? Only when using `mvn jetty:run`
#org.eclipse.jetty.annotations.AnnotationParser=ERROR
#org.eclipse.jetty.ee8.annotations.AnnotationParser=ERROR
#org.eclipse.jetty.ee10.annotations.AnnotationParser=ERROR
